version: "3.7"
services:
  bch-fe-prod:
    image: 127.0.0.1:5000/bch-fe
    build: .
    ports:
      - target: 80
        published: 80
        mode: host
    environment:
      REACT_APP_DP_ENV: production
