env:
  COMPOSE_FILE: docker-compose.pipeline.yml

steps:
  - label: ":docker: Build"
    plugins:
      - docker-compose#v3.9.0:
          build: app

  - wait

  - label: ":docker: Test %n"
    command: npm run pipelineTest
    plugins:
      - docker-compose#v3.9.0:
          run: app
