steps:
  - label: ":docker: Test"
    command: npm run pipelineTest
    plugins:
      - docker-compose#v3.9.0:
          run: ut
          config: docker-compose.pipeline.ut.yml

  - wait

  - label: ":docker: Build"
    command: ./ops/build

  - wait

  - label: ":battery: Publish Image"
    command: ./ops/pushImage

  - wait

  - label: ":rocket: Deploy"
    command: ./ops/deploy
