env:
  COMPOSE_FILE: docker-compose.pipeline.yml

steps:
  - label: ":docker: Build"
    artifact_paths: "/app/build/*"
    plugins:
      - docker-compose#v3.9.0:
          build: app
          volumes:
            - "./build:/app/build"
          # image-repository: index.docker.io/myorg/myrepo

  - wait

  - label: ":docker: Test %n"
    command: npm run pipelineTest
    plugins:
      - docker-compose#v3.9.0:
          run: app
