steps:
  - label: ":docker: Build"
    plugins:
      - docker-compose#v3.9.0:
          build: app

  - wait

  - label: ":docker: Test %n"
    command: npm run test
    parallelism: 25
    plugins:
      - docker-compose#v3.9.0:
          run: app
